name: Build Site

on:
  workflow_dispatch:

jobs:
  build_site:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        hugo-version: ["0.140.2"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo ${{ matrix.hugo-version }}
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ matrix.hugo-version }}
          extended: true

      - name: Build Hugo site
        run: |
          make build

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: site-build-${{ github.sha }}
          path: |
            public
          compression-level: 9
